### ISSUE TITLE
[Bug] Steamship is not a Vehicle

### ISSUE THREAD

**Issue by spannerman79** [GotoLink/pchan3#3]
Forge: 1448
MC: 1.7.10
Mod Version: 0.7
SMP

When running any sort of Anti Lag mod (Lag'B'Gon/LagFix) the Steamship gets removed.

Its almost like the Steamship is classed as a mob entity and not a boat or minecart entity.

Is there any way to change/fix this or the actual identifier needed to add to the blacklist for Lag'B'Gone/LagFix?

**Comment by GotoLink** [comment]
There is no common factor between boat and minecart that horse or pig don't have. Everything is a (rideable) entity, nothing is a vehicle.
Airship entity id is pchan3.Airship
Steam boat id is pchan3.Steamboat

**Comment by spannerman79** [comment]
Thank you for the entity ID's, I'll test now to see, if all goes good and they don't get cleared out by Lag'B'Gone or Lagfix I'll close this issue :smile:

**Comment by spannerman79** [comment]
Ok it looks like its `entity.pchan3.Airship.name` for the Airship and `entity.pchan3.SteamBoat.name` for the Steamboat.

Adding just `pchan3.Airship` or `pchan3.Steamboat` doesn't work

**Comment by GotoLink** [comment]
Well that is your "Anti Lag" mod format.
Closing then ?
